# -*- coding: utf-8 -*-
"""Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LQUOm3XJb0zYsAhtlgkDXWDb_b2MCpxl
"""

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('stopwords')

import random
import re
import numpy as np

import string
import re
import pickle
import matplotlib.pyplot as plt

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics.pairwise import cosine_similarity

knowledge_base = {

    "greeting": {
        "patterns": [
            "hello", "hi", "hey", "good morning", "good evening",
            "hi there", "hey there", "hello there"
        ],
        "response": "Hello! How can I help you?"
    },

    "farewell": {
        "patterns": [
            "bye", "goodbye", "see you", "bye bye",
            "see you later", "talk to you later", "exit"
        ],
        "response": "Goodbye! Have a nice day."
    },

    "admission": {
        "patterns": [
            "how to apply", "admission process", "how can i get admission",
            "apply for college", "admission requirements",
            "how to join", "application procedure"
        ],
        "response": "You can apply online through our official website."
    },

    "fees": {
        "patterns": [
            "fees", "course fees", "tuition fees", "how much is fee",
            "fee structure", "cost of course", "price of course",
            "what is the fee"
        ],
        "response": "The fee structure varies by course. Please check the website."
    },

    "courses": {
        "patterns": [
            "what courses are available", "courses offered", "list of courses",
            "what can i study", "available programs",
            "degree courses", "what subjects are there"
        ],
        "response": "We offer various undergraduate and postgraduate programs."
    },

    "hostel": {
        "patterns": [
            "is hostel available", "hostel facility", "accommodation",
            "student housing", "do you provide hostel",
            "hostel fees", "room availability"
        ],
        "response": "Yes, hostel facilities are available for students."
    },

    "placements": {
        "patterns": [
            "placements", "job opportunities", "campus placements",
            "placement record", "companies visiting",
            "do you provide jobs", "placement support"
        ],
        "response": "We have a strong placement record with many companies."
    },

    "thanks": {
        "patterns": [
            "thanks", "thank you", "thanks a lot",
            "much appreciated", "thank you so much"
        ],
        "response": "You're welcome!"
    },

    "identity": {
        "patterns": [
            "who are you", "what are you", "are you a bot",
            "your name", "tell me about yourself"
        ],
        "response": "I am your virtual assistant chatbot."
    },

    "creator": {
        "patterns": [
            "who made you", "who created you",
            "your developer", "who built you"
        ],
        "response": "I was created by a developer."
    },

    "unknown": {
        "patterns": [],
        "response": "Sorry, I don't understand that."
    }
}

def preprocess(text):
    text = text.lower()
    text = text.strip()
    text = re.sub(r'[^\w\s]', '', text)
    return text


def regex_match(user_input):
    if re.search(r'fee|cost|price', user_input):
        return "fees"
    return None


def find_best_match(user_input):
    for intent, data in knowledge_base.items():
        for pattern in data["patterns"]:
            if pattern in user_input:
                return intent
    return "unknown"


def get_response_rule(user_input):
    user_input = preprocess(user_input)

    regex_intent = regex_match(user_input)
    if regex_intent:
        return knowledge_base[regex_intent]["response"]

    intent = find_best_match(user_input)
    return knowledge_base[intent]["response"]

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def advanced_preprocess(text):
    tokens = nltk.word_tokenize(text.lower())

    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
        if word not in stop_words and word not in string.punctuation
    ]

    return " ".join(tokens)

X = []
y = []

for intent, data in knowledge_base.items():
    for pattern in data["patterns"]:
        X.append(advanced_preprocess(pattern))
        y.append(intent)

vectorizer = TfidfVectorizer()
X_vec = vectorizer.fit_transform(X)

model = LogisticRegression()
model.fit(X_vec, y)

y_pred = model.predict(X_vec)

accuracy = accuracy_score(y, y_pred) * 100
print("Training Accuracy: {:.2f}%".format(accuracy))

def predict_intent_cosine(user_input):
    processed = advanced_preprocess(user_input)
    vec = vectorizer.transform([processed])

    similarity = cosine_similarity(vec, X_vec)
    index = similarity.argmax()

    return y[index]

def get_nlp_response(user_input):
    intent = predict_intent_cosine(user_input)
    print("[NLP detected intent]:", intent)

    return knowledge_base[intent]["response"]

test_inputs = [
    "hey buddy",
    "how much does it cost",
    "tell me courses available",
    "do you have hostel rooms",
    "who is your creator"
]

for q in test_inputs:
    print("Q:", q)
    print("A:", get_nlp_response(q))
    print()

cm = confusion_matrix(y, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()

plt.savefig("confusion_matrix.png")
plt.show()

# Save
with open("model.pkl", "wb") as f:
    pickle.dump((model, vectorizer), f)

# Load
def load_model():
    with open("model.pkl", "rb") as f:
        return pickle.load(f)

model, vectorizer = load_model()

while True:
    user_input = input("You: ")

    if user_input.lower() == "exit":
        print("Bot: Goodbye!")
        break

    response = get_nlp_response(user_input)
    print("Bot:", response)